In [5]:
import os
import cv2
import numpy as np 
import pandas as pd
from IPython.display import display
data = pd.read_csv('balance.csv')
data = data.set_index(['Country','Year'])
data

                                              Maize and products  Vegetables  \
Country                                 Year
Afghanistan                             2014                22.0        33.0
                                        2015                13.0        26.0
                                        2016                15.0        43.0
                                        2017                11.0        34.0
                                        2018                15.0        22.0
...                                                          ...         ...
Net Food Importing Developing Countries 2014               268.0        42.0
                                        2015               270.0        42.0
                                        2016               273.0        42.0
                                        2017               277.0        41.0
                                        2018               271.0        42.0

                                              Meat  Eggs
Country                                 Year
Afghanistan                             2014  71.0   7.0
                                        2015  65.0   7.0
                                        2016  61.0   7.0
                                        2017  56.0   7.0
                                        2018  55.0   6.0
...                                            ...   ...
Net Food Importing Developing Countries 2014  89.0  11.0
                                        2015  86.0  11.0
                                        2016  84.0  10.0
                                        2017  83.0  11.0
                                        2018  85.0  11.0

[1025 rows x 4 columns]

In [7]:
data2 = pd.read_csv('regression.csv')
data2 = data2.set_index(['Country','Year'])
data2

,,Total Energy,Fertilizer,Consumption in Agriculture,Government_Management,Law&Political Stability,Unemployment_rate,Yield(hg/ha),Gini_Index,CPI,Male/Female,Rural/Urban,Developed,socre
Country,Year,,,,,,,,,,,,,
Afghanistan,2000,74174.8829,0.64,432.0000,-1.350000,-2.630000,11.517000,57031.55319,29.000000,3.951382e+01,1.059369,3.529414,2,2.815037
Albania,2000,77392.1087,26.75,33540.0000,-0.560000,-1.030000,16.573000,93010.24194,31.740000,6.660077e+01,1.024432,1.395734,1,3.461113
Algeria,2000,74132.7500,11.27,0.0000,-1.060000,-0.920000,29.770000,55748.24286,27.620000,5.542482e+01,1.027428,0.668931,1,3.121974
Angola,2000,74182.8939,0.42,516.0000,-1.520000,-1.180000,3.837000,45371.66667,51.960000,1.812510e+00,0.989632,0.996512,2,1.896367
Antigua and Barbuda,2000,100294.5043,0.00,282880.2545,1.270000,-2.050000,8.394268,50049.87097,39.583658,7.349858e+01,0.886170,2.112650,1,3.307945
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),2019,81002.4751,139.67,70692.0000,-0.068282,0.245215,6.896713,127383.85510,37.791460,2.633984e+08,0.970604,0.133276,1,0.385091
Viet Nam,2019,89276.2317,251.76,155832.0000,-0.068282,0.245215,6.896713,101925.65380,37.791460,1.131217e+02,0.996700,1.730120,1,3.296598
Yemen,2019,76138.5091,3.03,20640.0000,-0.068282,0.245215,6.896713,63858.63077,36.710000,1.844438e+02,1.015387,1.682885,2,2.537962
Zambia,2019,75235.9175,52.02,11352.0000,-0.700000,0.490000,11.425000,98222.17949,57.140000,1.476608e+02,0.980638,1.269019,2,2.604234
Zimbabwe,2019,78645.7082,37.41,46440.0000,-1.510000,0.410000,4.954000,59913.22892,40.362500,3.893035e+02,0.911413,2.104625,1,1.902345

In [9]:
data = pd.merge(data,data2,left_index=True,right_index=True,
               how = 'left')

                                              Maize and products  Vegetables  \
Country                                 Year
Afghanistan                             2014                22.0        33.0
                                        2015                13.0        26.0
                                        2016                15.0        43.0
                                        2017                11.0        34.0
                                        2018                15.0        22.0
...                                                          ...         ...
Net Food Importing Developing Countries 2014               268.0        42.0
                                        2015               270.0        42.0
                                        2016               273.0        42.0
                                        2017               277.0        41.0
                                        2018               271.0        42.0

                                              Meat  Eggs  Total Energy  \
Country                                 Year
Afghanistan                             2014  71.0   7.0    74610.4445
                                        2015  65.0   7.0    74613.9188
                                        2016  61.0   7.0    74594.3766
                                        2017  56.0   7.0    74608.2732
                                        2018  55.0   6.0    74632.1579
...                                            ...   ...           ...
Net Food Importing Developing Countries 2014  89.0  11.0           NaN
                                        2015  86.0  11.0           NaN
                                        2016  84.0  10.0           NaN
                                        2017  83.0  11.0           NaN
                                        2018  85.0  11.0           NaN

                                              Fertilizer  \
Country                                 Year
Afghanistan                             2014        9.99
                                        2015        3.94
                                        2016       13.37
                                        2017       19.91
                                        2018        7.45
...                                                  ...
Net Food Importing Developing Countries 2014         NaN
                                        2015         NaN
                                        2016         NaN
                                        2017         NaN
                                        2018         NaN

                                              Consumption in Agriculture  \
Country                                 Year
Afghanistan                             2014                     4752.00
                                        2015                     4786.56
                                        2016                     4592.16
                                        2017                     4730.40
                                        2018                     4968.00
...                                                                  ...
Net Food Importing Developing Countries 2014                         NaN
                                        2015                         NaN
                                        2016                         NaN
                                        2017                         NaN
                                        2018                         NaN

                                              Government_Management  \
Country                                 Year
Afghanistan                             2014                  -1.53
                                        2015                  -1.52
                                        2016                  -1.55
                                        2017                  -1.57
                                        2018                  -1.56
...                                                             ...
Net Food Importing Developing Countries 2014                    NaN
                                        2015                    NaN
                                        2016                    NaN
                                        2017                    NaN
                                        2018                    NaN

                                              Law&Political Stability  \
Country                                 Year
Afghanistan                             2014                    -0.18
                                        2015                    -0.16
                                        2016                    -0.22
                                        2017                    -0.22
                                        2018                    -0.22
...                                                               ...
Net Food Importing Developing Countries 2014                      NaN
                                        2015                      NaN
                                        2016                      NaN
                                        2017                      NaN
                                        2018                      NaN

                                              Unemployment_rate  Yield(hg/ha)  \
Country                                 Year
Afghanistan                             2014             11.448   61780.87234
                                        2015             11.387   52483.54167
                                        2016             11.313   47713.20833
                                        2017             11.184   59458.27083
                                        2018             11.057   59898.12500
...                                                         ...           ...
Net Food Importing Developing Countries 2014                NaN           NaN
                                        2015                NaN           NaN
                                        2016                NaN           NaN
                                        2017                NaN           NaN
                                        2018                NaN           NaN

                                              Gini_Index         CPI  \
Country                                 Year
Afghanistan                             2014        31.0  100.677773
                                        2015        31.0  100.011579
                                        2016        31.0  104.395978
                                        2017        31.0  109.590672
                                        2018        31.0  110.276872
...                                                  ...         ...
Net Food Importing Developing Countries 2014         NaN         NaN
                                        2015         NaN         NaN
                                        2016         NaN         NaN
                                        2017         NaN         NaN
                                        2018         NaN         NaN

                                              Male/Female  Rural/Urban  \
Country                                 Year
Afghanistan                             2014     1.055865     3.067186
                                        2015     1.057315     3.031814
                                        2016     1.057627     2.996803
                                        2017     1.057122     2.960340
                                        2018     1.056097     2.922354
...                                                   ...          ...
Net Food Importing Developing Countries 2014          NaN          NaN
                                        2015          NaN          NaN
                                        2016          NaN          NaN
                                        2017          NaN          NaN
                                        2018          NaN          NaN

                                              Developed     socre
Country                                 Year
Afghanistan                             2014        2.0  2.671597
                                        2015        2.0  2.793703
                                        2016        2.0  2.802497
                                        2017        2.0  2.776274
                                        2018        2.0  2.862970
...                                                 ...       ...
Net Food Importing Developing Countries 2014        NaN       NaN
                                        2015        NaN       NaN
                                        2016        NaN       NaN
                                        2017        NaN       NaN
                                        2018        NaN       NaN

[1025 rows x 17 columns]

In [10]:
data.to_csv('result.csv')

In [3]:
for file in files_name:
    file_path = path + "\\" + file
    data = pd.read_csv(file_path)
    data.set_index(['Area','Year'],inplace=True)
    all_data = pd.merge(all_data, data, left_index=True, right_index=True, how='left')
all_data = all_data.reset_index()
all_data

,Area,Year,Conflict and Disaster Stock Displacement Number,Producer Price Anuual Value,Total Population,Male/Female,Rural/Urban,\nPer capita arable land area,Consumption in Agriculture,Emissions (CH4) (Energy),...,Net exports Value,Gini_Index,Unemployment_rate,Government_Management,Law&Political Stability,Forest cover rate,"Consumer Prices, Food Indices (2015 = 100)","Consumer Prices, General Indices (2015 = 100)",Food price inflation,Fertilizer
0,Afghanistan,2000,NaN,95.370896,20779953.0,1.059369,3.529414,0.38,432.0,0.1440,...,-2177409,NaN,11.517,-1.35,-2.63,2.067825,34.037261,39.513817,NaN,0.64
1,Afghanistan,2001,NaN,92.137015,21606988.0,1.059920,3.510722,0.37,432.0,0.1440,...,-2789795,NaN,11.513,NaN,NaN,2.067825,36.992813,41.891307,0.086833,2.37
2,Afghanistan,2002,NaN,95.093134,22600770.0,1.062365,3.492104,0.36,648.0,0.2160,...,-3666795,NaN,11.596,-1.30,-2.15,2.067825,40.204987,44.400101,0.086832,3.16
3,Afghanistan,2003,NaN,91.669701,23680871.0,1.065270,3.473584,0.34,648.0,0.2160,...,-3884278,NaN,11.604,-1.20,-1.87,2.067825,43.696067,47.081529,0.086832,3.42
4,Afghanistan,2004,NaN,95.869104,24726684.0,1.066937,3.444361,0.33,864.0,0.2880,...,-4057358,NaN,11.528,-1.33,-1.17,2.067825,47.490269,48.671697,0.086832,4.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3755,Zimbabwe,2015,800.0,94.637895,13814629.0,0.906556,2.087875,0.25,53664.0,0.2232,...,-1017437,NaN,5.302,-1.53,0.51,36.350006,100.013064,100.003051,-0.033462,22.34
3756,Zimbabwe,2016,400.0,105.519649,14030331.0,0.907298,2.096375,0.29,44892.0,0.1860,...,-1011766,NaN,5.253,-1.52,0.47,35.542457,96.757053,98.436590,-0.032404,31.71
3757,Zimbabwe,2017,10000.0,107.314912,14236595.0,0.908508,2.102013,NaN,46440.0,0.1932,...,593992,NaN,5.168,-1.53,0.49,35.542457,99.172196,99.332101,0.025020,37.41
3758,Zimbabwe,2018,1100.0,105.519649,14438802.0,0.909973,2.104767,NaN,46440.0,0.1932,...,1105954,NaN,5.087,-1.50,0.50,35.542457,113.702593,109.672648,0.143887,37.41
3759,Zimbabwe,2019,104000.0,105.519649,14645468.0,0.911413,2.104625,NaN,NaN,NaN,...,2500976,NaN,4.954,-1.51,0.41,35.542457,517.329612,389.303450,3.233338,NaN

In [4]:
new = pd.DataFrame()

# using the area mean
for area in all_data['Area'].unique():
    df = all_data[all_data['Area']==area]
    df.fillna(method = 'backfill',inplace=True)
    new = pd.concat([new,df],axis=0)
all_data = new

# using the area mean
new = pd.DataFrame()
for area in all_data['Area'].unique():
    df = all_data[all_data['Area']==area]
    df.fillna(method = 'pad',inplace=True)
    new = pd.concat([new,df],axis=0)
all_data = new

# using this year mean
new = pd.DataFrame()
for year in all_data['Year'].unique():
    print(year)
    df = all_data[all_data['Year']==year]
    for column in list(df.columns[df.isnull().sum() > 0]):
        mean_val = df[column].mean()
        df[column].fillna(mean_val, inplace=True)
    new = pd.concat([new,df],axis=0)
all_data = new
all_data = all_data.set_index(['Area','Year'])
all_data

D:\ANACONDA\lib\site-packages\pandas\core\frame.py:4317: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

2000
2001
2002
2003
2004
2005
2006
2007
2008

D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(
D:\ANACONDA\lib\site-packages\pandas\core\series.py:4517: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().fillna(

2009
2010
2011
2012
2013
2014
2015
2016
2017
2018
2019

,,Conflict and Disaster Stock Displacement Number,Producer Price Anuual Value,Total Population,Male/Female,Rural/Urban,\nPer capita arable land area,Consumption in Agriculture,Emissions (CH4) (Energy),Emissions (CO2) (Energy),Emissions (CO2eq) (Energy),...,Net exports Value,Gini_Index,Unemployment_rate,Government_Management,Law&Political Stability,Forest cover rate,"Consumer Prices, Food Indices (2015 = 100)","Consumer Prices, General Indices (2015 = 100)",Food price inflation,Fertilizer
Area,Year,,,,,,,,,,,,,,,,,,,,,
Afghanistan,2000,3400.0,95.370896,20779953.0,1.059369,3.529414,0.380000,432.000000,0.144000,33.328800,36.724800,...,-2177409,29.000000,11.517000,-1.350000,-2.630000,2.067825,3.403726e+01,3.951382e+01,0.086833,0.64
Albania,2000,150.0,72.602660,3129243.0,1.024432,1.395734,0.250625,33540.000000,0.139200,2485.314000,2785.603200,...,-1844081,31.740000,16.573000,-0.560000,-1.030000,28.076642,6.344153e+01,6.660077e+01,0.021930,26.75
Algeria,2000,25000.0,54.095619,31042235.0,1.027428,0.668931,0.250625,0.000000,0.000000,0.000000,0.000000,...,662242,27.620000,29.770000,-1.060000,-0.920000,0.662961,5.189481e+01,5.542482e+01,0.013667,11.27
Angola,2000,86000.0,104.025401,16395473.0,0.989632,0.996512,0.250625,516.000000,0.002400,38.235600,42.855600,...,2592853,51.960000,3.837000,-1.520000,-1.180000,47.908879,1.181357e+00,1.812510e+00,1.851949,0.42
Antigua and Barbuda,2000,45.0,57.494706,76016.0,0.886170,2.112650,0.250625,282880.254511,1.745104,21232.240496,23762.476119,...,-506213,39.583658,8.394268,1.270000,-2.050000,22.727273,6.258868e+01,7.349858e+01,0.025332,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Venezuela (Bolivarian Republic of),2019,10000.0,21.069213,28515829.0,0.970604,0.133276,0.219000,70692.000000,0.292800,5238.277200,5871.193200,...,-8451263,37.791461,6.896713,-0.068282,0.245215,29.989947,4.623971e+08,2.633984e+08,1434.915544,139.67
Viet Nam,2019,96200.0,65.090678,96462106.0,0.996700,1.730120,0.219000,155832.000000,0.646800,11547.151200,12942.338400,...,-4417895,37.791461,6.896713,-0.068282,0.245215,29.989947,1.087972e+02,1.131217e+02,0.040789,251.76
Yemen,2019,10000.0,65.896369,29161922.0,1.015387,1.682885,0.219000,20640.000000,0.085200,1529.424000,1714.216800,...,-11841381,36.710000,6.896713,-0.068282,0.245215,29.989947,1.220177e+02,1.844438e+02,0.047224,3.03
Zambia,2019,1400.0,79.715649,17861030.0,0.980638,1.269019,0.219000,11352.000000,0.046800,841.183200,942.819600,...,601289,57.140000,11.425000,-0.700000,0.490000,65.199153,1.521539e+02,1.476608e+02,0.104033,52.02
Zimbabwe,2019,104000.0,105.519649,14645468.0,0.911413,2.104625,0.290000,46440.000000,0.193200,3441.204000,3856.988400,...,2500976,40.362500,4.954000,-1.510000,0.410000,35.542457,5.173296e+02,3.893035e+02,3.233338,37.41

In [5]:
all_data.to_csv('model_data.csv')