In [8]:
import os
from IPython.display import display
import pandas as pd 
import numpy as np 
path = r'D:\PyCharmproject\American\E\人均耕地面积\raw_data'
files_name = os.listdir(path)
original = pd.DataFrame()
for files in files_name:
    file  = path + "\\" + files
    data = pd.read_excel(file)
    data.drop('序号',axis = 1 , inplace=True)
    data.set_index('时间',inplace=True)
    original  = pd.concat([original,data],axis=1)
data = original
data.reset_index(inplace=True)
data

,时间,科威特:人均耕地面积,马尔代夫:人均耕地面积,也门共和国:人均耕地面积,比利时:人均耕地面积,马约特岛:人均耕地面积,日本:人均耕地面积,俄罗斯联邦:人均耕地面积,巴巴多斯:人均耕地面积,菲律宾:人均耕地面积,...,巴拿马:人均耕地面积,缅甸:人均耕地面积,安提瓜和巴布达:人均耕地面积,黎巴嫩:人均耕地面积,尼泊尔:人均耕地面积,塔吉克斯坦:人均耕地面积,津巴布韦:人均耕地面积,哥伦比亚:人均耕地面积,几内亚(比绍):人均耕地面积,埃及:人均耕地面积
0,2016,0.00,0.01,0.05,0.07,NaN,0.03,0.85,0.02,0.05,...,0.14,0.21,0.04,0.02,0.08,0.08,0.29,0.04,0.17,0.03
1,2015,0.00,0.01,0.05,0.07,NaN,0.03,0.85,0.04,0.05,...,0.14,0.21,0.04,0.02,0.07,0.09,0.25,0.04,0.17,0.03
2,2014,0.00,0.01,0.05,0.07,NaN,0.03,0.86,0.04,0.06,...,0.15,0.20,0.04,0.02,0.08,0.09,0.26,0.04,0.17,0.03
3,2013,0.00,0.01,0.05,0.07,NaN,0.03,0.85,0.04,0.06,...,0.15,0.20,0.04,0.03,0.08,0.11,0.27,0.04,0.17,0.03
4,2012,0.00,0.01,0.05,0.07,NaN,0.03,0.84,0.04,0.06,...,0.14,0.20,0.04,0.05,0.08,0.11,0.29,0.03,0.18,0.03
5,2011,0.00,0.01,0.05,0.07,NaN,0.03,0.85,0.04,0.06,...,0.15,0.22,0.04,0.03,0.08,0.12,0.32,0.04,0.19,0.03
6,2010,0.00,0.01,0.06,0.08,NaN,0.03,0.84,0.04,0.06,...,0.15,0.21,0.05,0.03,0.09,0.11,0.31,0.04,0.19,0.04
7,2009,0.00,0.01,0.05,0.08,0.04,0.03,0.86,0.06,0.06,...,0.16,0.23,0.09,0.03,0.08,0.11,0.34,0.04,0.20,0.04
8,2008,0.00,0.01,0.06,0.08,0.04,0.03,0.86,0.06,0.06,...,0.16,0.23,0.09,0.03,0.08,0.11,0.34,0.04,0.21,0.03
9,2007,0.00,0.01,0.06,0.08,0.04,0.03,0.86,0.06,0.06,...,0.16,0.23,0.09,0.03,0.08,0.11,0.32,0.05,0.21,0.03
10,2006,0.00,0.01,0.06,0.08,0.04,0.03,0.85,0.06,0.06,...,0.17,0.22,0.09,0.04,0.08,0.11,0.32,0.04,0.21,0.03
11,2005,0.01,0.01,0.07,0.08,0.04,0.03,0.85,0.05,0.07,...,0.17,0.21,0.10,0.05,0.09,0.14,0.25,0.04,0.19,0.04
12,2004,0.01,0.01,0.07,0.08,0.04,0.03,0.85,0.06,0.07,...,0.17,0.21,0.10,0.05,0.09,0.14,0.25,0.05,0.19,0.04
13,2003,0.01,0.01,0.08,0.08,0.04,0.03,0.85,0.06,0.07,...,0.18,0.21,0.10,0.05,0.09,0.15,0.25,0.05,0.20,0.04
14,2002,0.01,0.01,0.08,0.08,NaN,0.03,0.85,0.06,0.07,...,0.18,0.21,0.10,0.05,0.09,0.15,0.25,0.05,0.21,0.04
15,2001,0.01,0.01,0.08,0.08,NaN,0.03,0.85,0.06,0.07,...,0.18,0.22,0.10,0.04,0.09,0.15,0.25,0.06,0.21,0.04
16,2000,0.00,0.01,0.08,0.08,NaN,0.04,0.85,0.06,0.07,...,0.18,0.22,0.10,0.05,0.10,0.15,0.25,0.07,0.22,0.04
17,1999,0.00,0.01,0.09,0.08,NaN,0.04,0.85,0.06,0.08,...,0.18,0.21,0.11,0.05,0.10,0.15,0.26,0.06,0.23,0.05
18,1998,0.00,0.02,0.09,0.08,NaN,0.04,0.86,0.06,0.08,...,0.18,0.21,0.11,0.05,0.10,0.15,0.26,0.06,0.23,0.04
19,1997,0.00,0.02,0.10,0.08,NaN,0.04,0.87,0.06,0.08,...,0.18,0.22,0.11,0.05,0.10,0.15,0.27,0.06,0.24,0.05
20,1996,0.00,0.02,0.10,0.08,NaN,0.04,0.85,0.06,0.08,...,0.18,0.22,0.11,0.05,0.10,0.15,0.26,0.06,0.24,0.05
21,1995,0.00,0.02,0.11,0.08,NaN,0.04,0.86,0.06,0.08,...,0.19,0.22,0.12,0.05,0.11,0.15,0.26,0.06,0.25,0.05
22,1994,NaN,0.02,0.11,0.09,NaN,0.04,0.87,0.06,0.08,...,0.19,0.22,0.12,0.05,0.11,0.15,0.26,0.08,0.26,0.05
23,1993,NaN,0.02,0.11,0.08,NaN,0.04,0.87,0.06,0.08,...,0.20,0.23,0.12,0.05,0.11,0.15,0.27,0.08,0.27,0.05
24,1992,NaN,0.02,0.10,0.08,NaN,0.04,0.89,0.06,0.09,...,0.20,0.23,0.13,0.06,0.12,0.16,0.27,0.08,0.28,0.04
25,1991,0.00,0.02,0.12,0.07,NaN,0.04,0.91,0.06,0.09,...,0.20,0.23,0.13,0.06,0.12,0.16,0.27,0.09,0.29,0.04
26,1990,0.00,0.02,0.12,0.07,NaN,0.04,0.92,0.06,0.09,...,0.21,0.24,0.13,0.06,0.12,0.17,0.28,0.09,0.30,0.04
27,1989,0.00,0.02,0.12,0.07,NaN,0.04,0.92,0.06,0.09,...,0.21,0.24,0.13,0.06,0.12,0.17,0.28,0.10,0.30,0.04
28,1988,0.00,0.02,0.12,0.07,NaN,0.04,0.93,0.06,0.09,...,0.21,0.25,0.13,0.06,0.13,0.18,0.29,0.11,0.31,0.04
29,1987,0.00,0.02,0.13,0.06,NaN,0.04,0.94,0.06,0.10,...,0.21,0.25,0.12,0.06,0.13,0.18,0.29,0.12,0.32,0.04
30,1986,0.00,0.02,0.13,0.07,NaN,0.04,0.95,0.06,0.10,...,0.21,0.26,0.12,0.07,0.13,0.19,0.30,0.12,0.33,0.05
31,1985,0.00,0.02,0.14,0.07,NaN,0.04,0.95,0.06,0.10,...,0.21,0.26,0.12,0.07,0.13,0.20,0.30,0.12,0.33,0.05
32,1984,0.00,0.02,0.14,0.07,NaN,0.04,0.96,0.06,0.10,...,0.22,0.27,0.12,0.07,0.14,0.20,0.31,0.12,0.33,0.05
33,1983,0.00,0.02,0.15,0.07,NaN,0.04,0.97,0.06,0.10,...,0.22,0.27,0.11,0.07,0.14,0.21,0.32,0.12,0.33,0.05
34,1982,0.00,0.02,0.15,0.07,NaN,0.04,0.97,0.06,0.10,...,0.22,0.28,0.11,0.07,0.14,0.21,0.33,0.13,0.32,0.05
35,1981,0.00,0.02,0.16,0.07,NaN,0.04,0.98,0.06,0.11,...,0.22,0.28,0.11,0.07,0.15,0.22,0.34,0.13,0.31,0.05
36,1980,0.00,0.03,0.16,0.07,NaN,0.04,0.98,0.06,0.11,...,0.22,0.29,0.11,0.08,0.15,0.23,0.34,0.13,0.32,0.05
37,1979,0.00,0.03,0.17,0.09,NaN,0.04,0.99,0.06,0.11,...,0.23,0.29,0.11,0.08,0.15,0.23,0.35,0.13,0.33,0.05
38,1978,0.00,0.03,0.18,0.09,NaN,0.04,1.00,0.06,0.11,...,0.23,0.30,0.11,0.08,0.15,0.24,0.36,0.14,0.35,0.06
39,1977,0.00,0.03,0.18,0.09,NaN,0.04,1.01,0.06,0.11,...,0.24,0.31,0.11,0.08,0.16,0.25,0.37,0.14,0.36,0.06
40,1976,0.00,0.03,0.19,0.09,NaN,0.04,1.02,0.06,0.12,...,0.24,0.31,0.10,0.08,0.16,0.25,0.39,0.14,0.38,0.06
41,1975,0.00,0.03,0.19,0.09,NaN,0.04,1.02,0.07,0.12,...,0.25,0.32,0.10,0.09,0.16,0.26,0.40,0.14,0.39,0.07
42,1974,0.00,0.03,0.20,0.09,NaN,0.05,1.03,0.07,0.12,...,0.26,0.33,0.11,0.09,0.16,0.27,0.41,0.15,0.40,0.07
43,1973,0.00,0.02,0.20,0.09,NaN,0.05,1.04,0.07,0.12,...,0.26,0.33,0.11,0.09,0.17,0.28,0.42,0.15,0.41,0.07
44,1972,0.00,0.02,0.20,0.10,NaN,0.05,1.04,0.07,0.12,...,0.27,0.36,0.11,0.09,0.16,0.29,0.43,0.15,0.41,0.07
45,1971,0.00,0.02,0.21,0.10,NaN,0.05,1.05,0.07,0.12,...,0.28,0.37,0.11,0.10,0.16,0.30,0.44,0.15,0.41,0.08
46,1970,0.00,0.02,0.21,0.10,NaN,0.05,1.06,0.07,0.13,...,0.29,0.38,0.12,0.10,0.16,0.31,0.45,0.16,0.42,0.08
47,1969,0.00,0.02,0.21,0.10,NaN,0.05,1.07,0.07,0.13,...,0.30,0.39,0.12,0.10,0.15,0.32,0.45,0.16,0.43,0.08
48,1968,0.00,0.02,0.21,0.10,NaN,0.05,1.07,0.07,0.14,...,0.31,0.40,0.11,0.10,0.16,0.33,0.46,0.17,0.43,0.08
49,1967,0.00,0.02,0.22,0.10,NaN,0.05,1.08,0.07,0.14,...,0.31,0.40,0.11,0.09,0.16,0.34,0.46,0.17,0.43,0.08
50,1966,0.00,0.02,0.22,0.10,NaN,0.05,1.09,0.07,0.15,...,0.33,0.41,0.13,0.09,0.16,0.35,0.47,0.18,0.42,0.08
51,1965,0.00,0.02,0.23,0.10,NaN,0.06,1.11,0.07,0.15,...,0.34,0.42,0.13,0.09,0.16,0.36,0.47,0.18,0.42,0.08
52,1964,0.00,0.02,0.23,0.10,NaN,0.06,1.12,0.07,0.16,...,0.35,0.43,0.12,0.09,0.17,0.38,0.48,0.19,0.42,0.08
53,1963,0.00,0.02,0.23,0.10,NaN,0.06,1.14,0.07,0.16,...,0.36,0.44,0.14,0.09,0.17,0.39,0.48,0.19,0.42,0.08
54,1962,0.00,0.02,0.23,0.10,NaN,0.06,1.16,0.07,0.17,...,0.37,0.45,0.12,0.09,0.17,0.41,0.48,0.20,0.42,0.08
55,1961,0.00,0.02,0.24,0.10,NaN,0.06,1.17,0.07,0.18,...,0.38,0.46,0.14,0.09,0.18,0.43,0.49,0.20,0.42,0.09

In [12]:
year_list = data.columns.tolist()
year_list = year_list[1:]
year_list

['科威特:人均耕地面积',
 '马尔代夫:人均耕地面积',
 '也门共和国:人均耕地面积',
 '比利时:人均耕地面积',
 '马约特岛:人均耕地面积',
 '日本:人均耕地面积',
 '俄罗斯联邦:人均耕地面积',
 '巴巴多斯:人均耕地面积',
 '菲律宾:人均耕地面积',
 '韩国:人均耕地面积',
 '老挝:人均耕地面积',
 '喀麦隆:人均耕地面积',
 '南斯拉夫(塞尔维亚和黑山):人均耕地面积',
 '伊拉克:人均耕地面积',
 '萨尔瓦多:人均耕地面积',
 '斯洛文尼亚:人均耕地面积',
 '加拿大:人均耕地面积',
 '乌克兰:人均耕地面积',
 '斐济:人均耕地面积',
 '保加利亚:人均耕地面积',
 '基里巴斯:人均耕地面积',
 '西海岸和加沙:人均耕地面积',
 '斯里兰卡:人均耕地面积',
 '莱索托:人均耕地面积',
 '立陶宛:人均耕地面积',
 '挪威:人均耕地面积',
 '马耳他:人均耕地面积',
 '阿根廷:人均耕地面积',
 '赤道几内亚:人均耕地面积',
 '列支敦士登:人均耕地面积',
 '玻利维亚:人均耕地面积',
 '圭亚那:人均耕地面积',
 '巴哈马:人均耕地面积',
 '乌拉圭:人均耕地面积',
 '爱尔兰:人均耕地面积',
 '曼岛:人均耕地面积',
 '卢旺达:人均耕地面积',
 '圣多美和普林西比:人均耕地面积',
 '塞拉利昂:人均耕地面积',
 '索马里:人均耕地面积',
 '南非:人均耕地面积',
 '坦桑尼亚:人均耕地面积',
 '多哥:人均耕地面积',
 '乌干达:人均耕地面积',
 '布基纳法索:人均耕地面积',
 '民主刚果:人均耕地面积',
 '斯威士兰:人均耕地面积',
 '厄立特里亚:人均耕地面积',
 '塞内加尔:人均耕地面积',
 '塞舌尔:人均耕地面积',
 '丹麦:人均耕地面积',
 '英国:人均耕地面积',
 '德国:人均耕地面积',
 '法国:人均耕地面积',
 '卢森堡:人均耕地面积',
 '希腊:人均耕地面积',
 '葡萄牙:人均耕地面积',
 '西班牙:人均耕地面积',
 '安道尔:人均耕地面积',
 '奥地利:人均耕地面积',
 '冰岛:人均耕地面积',
 '罗马尼亚:人均耕地面积',
 '北马里亚纳群岛:人均耕地面积',
 '瑞典:人均耕地面积',
 '拉脱维亚:人均耕地面积',
 '克罗地亚:人均耕地面积',
 '捷克:人均耕地面积',
 '斯洛伐克:人均耕地面积',
 '前南斯拉夫马其顿:人均耕地面积',
 '波斯尼亚—黑塞哥维那:人均耕地面积',
 '海峡群岛:人均耕地面积',
 '阿鲁巴岛:人均耕地面积',
 '伯利兹:人均耕地面积',
 '加蓬:人均耕地面积',
 '巴西:人均耕地面积',
 '智利:人均耕地面积',
 '多米尼加:人均耕地面积',
 '多米尼加共和国:人均耕地面积',
 '苏丹:人均耕地面积',
 '厄瓜多尔:人均耕地面积',
 '危地马拉:人均耕地面积',
 '海地:人均耕地面积',
 '牙买加:人均耕地面积',
 '墨西哥:人均耕地面积',
 '洪都拉斯:人均耕地面积',
 '尼加拉瓜:人均耕地面积',
 '秘鲁:人均耕地面积',
 '圣文森特和格林纳丁斯:人均耕地面积',
 '圣其茨--尼维斯:人均耕地面积',
 '马拉维:人均耕地面积',
 '拉丁美洲和加勒比海:人均耕地面积',
 '科特迪瓦共和国:人均耕地面积',
 '百慕大群岛:人均耕地面积',
 '吉尔吉斯斯坦:人均耕地面积',
 '关岛:人均耕地面积',
 '新喀里多尼亚:人均耕地面积',
 '瓦努阿图:人均耕地面积',
 '汤加:人均耕地面积',
 '萨摩亚:人均耕地面积',
 '密克罗尼西亚联邦:人均耕地面积',
 '美属维尔京群岛:人均耕地面积',
 '帕劳共和国:人均耕地面积',
 '荷兰:人均耕地面积',
 '阿富汗:人均耕地面积',
 '孟加拉国:人均耕地面积',
 '不丹:人均耕地面积',
 '柬埔寨:人均耕地面积',
 '文莱:人均耕地面积',
 '塞浦路斯:人均耕地面积',
 '朝鲜:人均耕地面积',
 '白俄罗斯:人均耕地面积',
 '印度:人均耕地面积',
 '伊朗:人均耕地面积',
 '以色列:人均耕地面积',
 '乌兹别克斯坦:人均耕地面积',
 '马来西亚:人均耕地面积',
 '蒙古:人均耕地面积',
 '阿曼:人均耕地面积',
 '巴基斯坦:人均耕地面积',
 '卡塔尔:人均耕地面积',
 '叙利亚:人均耕地面积',
 '泰国:人均耕地面积',
 '土耳其:人均耕地面积',
 '越南:人均耕地面积',
 '中国:人均耕地面积',
 '东帝汶:人均耕地面积',
 '哈萨克斯坦:人均耕地面积',
 '土库曼斯坦:人均耕地面积',
 '美国:人均耕地面积',
 '古巴:人均耕地面积',
 '中非:人均耕地面积',
 '刚果:人均耕地面积',
 '冈比亚:人均耕地面积',
 '利比里亚:人均耕地面积',
 '哥斯达黎加:人均耕地面积',
 '利比亚:人均耕地面积',
 '新西兰:人均耕地面积',
 '瑞士:人均耕地面积',
 '芬兰:人均耕地面积',
 '印度尼西亚:人均耕地面积',
 '匈牙利:人均耕地面积',
 '阿拉伯联合酋长国:人均耕地面积',
 '格鲁吉亚:人均耕地面积',
 '约旦:人均耕地面积',
 '巴拉圭:人均耕地面积',
 '波兰:人均耕地面积',
 '委内瑞拉:人均耕地面积',
 '新加坡:人均耕地面积',
 '巴拿马:人均耕地面积',
 '缅甸:人均耕地面积',
 '安提瓜和巴布达:人均耕地面积',
 '黎巴嫩:人均耕地面积',
 '尼泊尔:人均耕地面积',
 '塔吉克斯坦:人均耕地面积',
 '津巴布韦:人均耕地面积',
 '哥伦比亚:人均耕地面积',
 '几内亚(比绍):人均耕地面积',
 '埃及:人均耕地面积']

In [13]:
all_data = []
for location in data['时间'].unique():
    print(location)
#     for item in data['Element'].unique():
    one_row = data[
        (data['时间'] == location)
    ]
    for year in year_list:
        one_data = []
        one_data.append(location)
#         one_data.append(item)
        one_data.append(year)
        try:
            one_data.append(one_row[year].values[0])

        except:
             one_data.append(np.nan)
        all_data.append(one_data)
all_data = pd.DataFrame(all_data)
all_data.columns = ['时间','地点','人均耕地面积']
all_data

2016
2015
2014
2013
2012
2011
2010
2009
2008
2007
2006
2005
2004
2003
2002
2001
2000
1999
1998
1997
1996
1995
1994
1993
1992
1991
1990
1989
1988
1987
1986
1985
1984
1983
1982
1981
1980
1979
1978
1977
1976
1975
1974
1973
1972
1971
1970
1969
1968
1967
1966
1965
1964
1963
1962
1961

        时间              地点  人均耕地面积
0     2016      科威特:人均耕地面积    0.00
1     2016     马尔代夫:人均耕地面积    0.01
2     2016    也门共和国:人均耕地面积    0.05
3     2016      比利时:人均耕地面积    0.07
4     2016     马约特岛:人均耕地面积     NaN
...    ...             ...     ...
8843  1961    塔吉克斯坦:人均耕地面积    0.43
8844  1961     津巴布韦:人均耕地面积    0.49
8845  1961     哥伦比亚:人均耕地面积    0.20
8846  1961  几内亚(比绍):人均耕地面积    0.42
8847  1961       埃及:人均耕地面积    0.09

[8848 rows x 3 columns]

In [15]:
all_data.to_excel('result.xlsx')