In [7]:
import pandas as pd 
data = pd.read_csv('LSTM_for_trump_result.csv')
data

,Day,C1,I,G,NX,new_cases,new_deaths,GDP
0,2015/1/2,-15.776760,76270000.0,1214.892,-435.900000,0.0,0.000000,2.610000e+11
1,2015/1/5,-16.496330,116160000.0,1214.892,-435.900000,0.0,0.000000,2.680000e+11
2,2015/1/6,-16.548551,101870000.0,1214.892,-435.900000,0.0,0.000000,2.650000e+11
3,2015/1/7,-13.489590,91030000.0,1214.892,-435.900000,0.0,0.000000,2.680000e+11
4,2015/1/8,-10.824681,114890000.0,1214.892,-435.900000,0.0,0.000000,2.670000e+11
...,...,...,...,...,...,...,...,...
1850,2021/11/24,7.459153,385072723.7,1570.000,-444.826228,0.0,0.000476,3.054950e+11
1851,2021/11/25,7.358248,384165347.8,1570.000,-400.494384,0.0,0.000436,3.057250e+11
1852,2021/11/26,7.855719,383372244.7,1570.000,-400.323036,2.0,0.000399,3.058620e+11
1853,2021/11/27,5.803862,384602916.3,1570.000,-400.686817,0.0,0.000365,3.052850e+11
1854,2021/11/28,6.257201,384383331.0,1570.000,-400.842700,0.0,0.000000,3.054120e+11

In [8]:
corr = data.corr()
corr.to_csv('trump_corr.csv')